server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8083}/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: userModule
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: accountModule
          uri: lb://account-service
          predicates:
            - Path=/account/**
        - id: walletModule
          uri: lb://wallet-service
          predicates:
            - Path=/wallet/**
        - id: historyModule
          uri: lb://history-service
          predicates:
            - Path=/history/**