server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8083}/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: userModule
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /api/v1/user/$\{path}
        - id: accountModule
          uri: lb://account-service
          predicates:
            - Path=/api/v1/account/**
          filters:
            - RewritePath=/account/(?<path>.*), /api/v1/account/$\{path}
        - id: walletModule
          uri: lb://wallet-service
          predicates:
            - Path=/api/v1/wallet/**
          filters:
            - RewritePath=/wallet/(?<path>.*), /api/v1/wallet/$\{path}
        - id: historyModule
          uri: lb://history-service
          predicates:
            - Path=/api/v1/history/**
          filters:
            - RewritePath=/history/(?<path>.*), /api/v1/history/$\{path}
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"