server:
  port: ${SERVER_PORT:0}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8083}/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    config:
      discovery:
        service-id: wallet-service
  data:
    web:
      pageable:
        one-indexed-parameters: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATA_SOURCE_URL:jdbc:postgresql://localhost:5433/wallet_db}
    username: ${SPRING_DATA_SOURCE_USERNAME:ppcc}
    password: ${SPRING_DATA_SOURCE_PASSWORD:ppcc}
  flyway:
    enabled: true
    check-location: true
    locations: classpath:migration
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:ppcc}
    password: ${SPRING_RABBITMQ_PASSWORD:ppcc}

ppcc:
  wallet:
    rabbitmq:
      queue: ${PPCC_WALLET_RABBITMQ_QUEUE:wallet.queue}
  user:
    rabbitmq:
      queue: ${PPCC_USER_RABBITMQ_QUEUE:user.queue}